
$enable_serial_logging = false

Vagrant.configure("2") do |config|
  config.vm.define :matchbox_client do |matchbox_client|

    matchbox_client.vm.box = 'c33s/empty'

    if $enable_serial_logging
      logdir = File.join(File.dirname(__FILE__), "log")
      FileUtils.mkdir_p(logdir)

      serialFile = File.join(logdir, "serial.txt")
      FileUtils.touch(serialFile)

      config.vm.provider :virtualbox do |vb, override|
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", serialFile]
      end
    end

    matchbox_client.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '2024'
      libvirt.cpus = '1'
      libvirt.storage :file, :size => '10G', :type => 'qcow2'
      libvirt.boot 'network'
      libvirt.mgmt_attach = 'false'
      libvirt.management_network_name = "pxe_network"
      libvirt.management_network_address = "192.168.0.0/24"
      libvirt.management_network_mode = "nat"
    end

    matchbox_client.vm.provider :virtualbox do |vb|
      vb.memory = '2048'
      vb.cpus = '1'
      vb.gui = 'true'

      vb.customize [
        'modifyvm', :id,
        '--nic1', 'intnet',
        '--intnet1', 'pxe_network',
        '--nic2', 'nat',
        '--boot1', 'disk',
        '--boot2', 'net',
        '--boot3', 'none',
        '--boot4', 'none'
      ]

      # Disable question about installation disk on first boot
      vb.customize [ 'setextradata', :id, 'GUI/FirstRun', 'no' ]

    end
  end
end
