Vagrant.configure("2") do |config|
  config.vm.define :matchbox_client do |matchbox_client|

    matchbox_client.vm.box = 'c33s/empty'

    matchbox_client.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '1024'
      libvirt.cpus = '1'
      libvirt.storage :file, :size => '10G', :type => 'qcow2'
      libvirt.boot 'network'
      libvirt.mgmt_attach = 'false'
      libvirt.management_network_name = "pxe_network"
      libvirt.management_network_address = "192.168.0.0/24"
      libvirt.management_network_mode = "nat"
    end

    matchbox_client.vm.provider :virtualbox do |vb|
      vb.memory = '2048'
      vb.cpus = '1'
      vb.gui = 'true'

      vb.customize [
        'modifyvm', :id,
        '--nic1', 'nat',
        '--nic2', 'intnet',
        '--intnet2', 'pxe_network',
        '--boot1', 'disk',
        '--boot2', 'net',
        '--boot3', 'none',
        '--boot4', 'none'
      ]

    end
  end
end
